app:
  datasource:
    main:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://localhost/sniperjerseydb
      username: PiousAn
      password: Pious123
      pool-size: 30

server:
  error:
    include-binding-errors: always
    include-message: always


flyway:
  url: jdbc:postgresql://localhost/sniperjerseydb
  user: PiousAn
  password: Pious123
  schemas: public
  locations: classpath:db/migration
  baselineOnMigrate: true
